version: '3.8'

services:
  finapp-backend:
    volumes:
      - ../finapp-backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  finapp-web:
    volumes:
      - ../finapp-web:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
